version: '3.8'

services:
  aflafrettir-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aflafrettir-admin
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
